export interface Channel {
  name: string;
  category: string;
}

export const CHANNELS: Channel[] = [
  { name: "Brozo", category: "Cultura e Variedades" },
  { name: "TV Pampa", category: "Cultura e Variedades" },
  { name: "SBT", category: "Cultura e Variedades" },
  { name: "RECORD", category: "Cultura e Variedades" },
  { name: "BAND", category: "Cultura e Variedades" },
  { name: "TRAVEL", category: "Cultura e Variedades" },
  { name: "TV BLITS", category: "Cultura e Variedades" },
  { name: "Planalto Norte", category: "Cultura e Variedades" },
  { name: "GAZETA", category: "Cultura e Variedades" },
  { name: "VRT", category: "Cultura e Variedades" },
  { name: "DOCS", category: "Cultura e Variedades" },
  { name: "Unique", category: "Cultura e Variedades" },
  { name: "Artel", category: "Cultura e Variedades" },
  { name: "Trace Brazuca", category: "Cultura e Variedades" },
  { name: "TV História", category: "Cultura e Variedades" },
  { name: "Music Box Brazil", category: "Cultura e Variedades" },
  { name: "TV Justiça", category: "Públicos" },
  { name: "TV Brasil", category: "Públicos" },
  { name: "RESERVADO COMUNITÁRIO", category: "Públicos" },
  { name: "TV Senado", category: "Públicos" },
  { name: "TV Câmara", category: "Públicos" },
  { name: "RedeTV", category: "Notícias" },
  { name: "New", category: "Notícias" },
  { name: "TVD News", category: "Notícias" },
  { name: "Euro News", category: "Notícias" },
  { name: "Band News", category: "Notícias" },
  { name: "RN", category: "Notícias" },
  { name: "CNN Brasil", category: "Notícias" },
  { name: "Telesur", category: "Notícias" },
  { name: "Exitosa", category: "Notícias" },
  { name: "Mider", category: "Filmes e Séries" },
  { name: "LMC", category: "Filmes e Séries" },
  { name: "Retro", category: "Filmes e Séries" },
  { name: "Ultra", category: "Filmes e Séries" },
  { name: "Family Series", category: "Filmes e Séries" },
  { name: "Movies", category: "Filmes e Séries" },
  { name: "Prime Box Brazil", category: "Filmes e Séries" },
  { name: "Film & Arts", category: "Filmes e Séries" },
  { name: "AMC", category: "Filmes e Séries" },
  { name: "ISTV", category: "Filmes e Séries" },
  { name: "Kios", category: "Infantil" },
  { name: "ID", category: "Infantil" },
  { name: "Otaku", category: "Infantil" },
  { name: "Lolly", category: "Infantil" },
  { name: "Yupi", category: "Infantil" },
  { name: "Hallo!", category: "Infantil" },
  { name: "Fish TV", category: "Esportes" },
  { name: "Unique", category: "Esportes" },
  { name: "Cazé TV", category: "Esportes" },
  { name: "Band Sports HD", category: "Esportes" },
  { name: "Canal Rural", category: "Agronegócio" },
  { name: "AgroBrasil", category: "Agronegócio" },
  { name: "Terra Viva", category: "Agronegócio" },
  { name: "AgroCanal", category: "Agronegócio" },
  { name: "TV Cultura", category: "Educativos" },
  { name: "Tvescala", category: "Educativos" },
  { name: "RESERVADO UNIVERSITÁRIO", category: "Educativos" },
  { name: "SescTV", category: "Educativos" },
  { name: "NHK", category: "Étnicos" },
];
