export interface Channel {
  name: string;
  category: string;
}

// Plus Plan Channels (updated)
export const PLUS_CHANNELS: Channel[] = [
  { category: "Cultura e Variedades", name: "Brozo" },
  { category: "Cultura e Variedades", name: "TV Pampa" },
  { category: "Cultura e Variedades", name: "SBT" },
  { category: "Cultura e Variedades", name: "RECORD" },
  { category: "Cultura e Variedades", name: "BAND" },
  { category: "Cultura e Variedades", name: "TRAVEL" },
  { category: "Cultura e Variedades", name: "TV BLITS" },
  { category: "Cultura e Variedades", name: "Planalto Norte" },
  { category: "Cultura e Variedades", name: "GAZETA" },
  { category: "Cultura e Variedades", name: "VRT" },
  { category: "Cultura e Variedades", name: "DOCS" },
  { category: "Cultura e Variedades", name: "Unique" },
  { category: "Cultura e Variedades", name: "Artel" },
  { category: "Cultura e Variedades", name: "Trace Brazuca" },
  { category: "Cultura e Variedades", name: "TV História" },
  { category: "Cultura e Variedades", name: "Music Box Brazil" },
  { category: "Cultura e Variedades", name: "Home & Health" },
  { category: "Cultura e Variedades", name: "TLC" },
  { category: "Cultura e Variedades", name: "Food Network" },
  { category: "Cultura e Variedades", name: "Int Novelas" },
  { category: "Públicos", name: "TV Justiça" },
  { category: "Públicos", name: "TV Brasil" },
  { category: "Públicos", name: "RESERVADO COMUNITÁRIO" },
  { category: "Públicos", name: "TV Senado" },
  { category: "Públicos", name: "TV Câmara" },
  { category: "Notícias", name: "RedeTV" },
  { category: "Notícias", name: "New" },
  { category: "Notícias", name: "TVD News" },
  { category: "Notícias", name: "Euro News" },
  { category: "Notícias", name: "Band News" },
  { category: "Notícias", name: "RN" },
  { category: "Notícias", name: "CNN Brasil" },
  { category: "Notícias", name: "Telesur" },
  { category: "Notícias", name: "Exitosa" },
  { category: "Notícias", name: "JP News" },
  { category: "Notícias", name: "Fox News" },
  { category: "Filmes e Séries", name: "Mider" },
  { category: "Filmes e Séries", name: "LMC" },
  { category: "Filmes e Séries", name: "Retro" },
  { category: "Filmes e Séries", name: "Ultra" },
  { category: "Filmes e Séries", name: "Family Series" },
  { category: "Filmes e Séries", name: "Movies" },
  { category: "Filmes e Séries", name: "Prime Box Brazil" },
  { category: "Filmes e Séries", name: "Film & Arts" },
  { category: "Filmes e Séries", name: "AMC" },
  { category: "Filmes e Séries", name: "ISTV" },
  { category: "Filmes e Séries", name: "Canal Sony" },
  { category: "Filmes e Séries", name: "TNT Series" },
  { category: "Filmes e Séries", name: "Space" },
  { category: "Filmes e Séries", name: "TCM HD" },
  { category: "Filmes e Séries", name: "Top Action" },
  { category: "Infantil", name: "Kios" },
  { category: "Infantil", name: "ID" },
  { category: "Infantil", name: "Otaku" },
  { category: "Infantil", name: "Lolly / Leo & Lully" },
  { category: "Infantil", name: "Yupi" },
  { category: "Infantil", name: "Hallo!" },
  { category: "Infantil", name: "Discovery Kids" },
  { category: "Infantil", name: "Cartoon Network" },
  { category: "Infantil", name: "Tooncast" },
  { category: "Infantil", name: "Cartoonito" },
  { category: "Esportes", name: "Fish TV" },
  { category: "Esportes", name: "Unique Sports" },
  { category: "Esportes", name: "Cazé TV" },
  { category: "Esportes", name: "Band Sports HD" },
  { category: "Esportes", name: "Fuel TV" },
  { category: "Esportes", name: "ESPN" },
  { category: "Esportes", name: "ESPN 4" },
  { category: "Esportes", name: "ESPN 5" },
  { category: "Esportes", name: "TNT Sports" },
  { category: "Agronegócio", name: "Canal Rural" },
  { category: "Agronegócio", name: "AgroBrasil" },
  { category: "Agronegócio", name: "Terra Viva" },
  { category: "Agronegócio", name: "AgroCanal" },
  { category: "Agronegócio", name: "Canal do Boi" },
  { category: "Documentários", name: "Discovery" },
  { category: "Documentários", name: "Animal Planet" },
  { category: "Documentários", name: "Discovery Turbo" },
  { category: "Documentários", name: "HGTV" },
  { category: "Educativos", name: "TV Cultura" },
  { category: "Educativos", name: "Tvescala" },
  { category: "Educativos", name: "RESERVADO UNIVERSITÁRIO" },
  { category: "Educativos", name: "SescTV" },
  { category: "Religiosos / Outros", name: "TV Mundo Maior" },
  { category: "Religiosos / Outros", name: "Canção Nova" },
  { category: "Religiosos / Outros", name: "Rede Vida" },
  { category: "Religiosos / Outros", name: "RS21" },
  { category: "Religiosos / Outros", name: "TV Evangelizar" },
  { category: "Religiosos / Outros", name: "Novo Tempo" },
  { category: "Religiosos / Outros", name: "EWTN" },
  { category: "Religiosos / Outros", name: "Rede Gênesis" },
  { category: "Étnicos", name: "NHK" },
];

// Ultra Plan Channels
export const ULTRA_CHANNELS: Channel[] = [
  { category: "Cultura e Variedades", name: "Brozo" },
  { category: "Cultura e Variedades", name: "TV Pampa" },
  { category: "Cultura e Variedades", name: "SBT" },
  { category: "Cultura e Variedades", name: "RECORD" },
  { category: "Cultura e Variedades", name: "BAND" },
  { category: "Cultura e Variedades", name: "TRAVEL" },
  { category: "Cultura e Variedades", name: "TV BLITS" },
  { category: "Cultura e Variedades", name: "Planalto Norte" },
  { category: "Cultura e Variedades", name: "GAZETA" },
  { category: "Cultura e Variedades", name: "VRT" },
  { category: "Cultura e Variedades", name: "DOCS" },
  { category: "Cultura e Variedades", name: "Unique" },
  { category: "Cultura e Variedades", name: "Artel" },
  { category: "Cultura e Variedades", name: "Trace Brazuca" },
  { category: "Cultura e Variedades", name: "Trace Latina" },
  { category: "Cultura e Variedades", name: "Trace Urban" },
  { category: "Cultura e Variedades", name: "TV História" },
  { category: "Cultura e Variedades", name: "Music Box Brazil" },
  { category: "Cultura e Variedades", name: "Home & Health" },
  { category: "Cultura e Variedades", name: "TLC" },
  { category: "Cultura e Variedades", name: "Food Network" },
  { category: "Cultura e Variedades", name: "Int Novelas" },
  { category: "Cultura e Variedades", name: "Rai Italia" },
  { category: "Cultura e Variedades", name: "Adult Swim" },
  { category: "Cultura e Variedades", name: "Sabor & Arte" },
  { category: "Públicos", name: "TV Justiça" },
  { category: "Públicos", name: "TV Brasil" },
  { category: "Públicos", name: "RESERVADO COMUNITÁRIO" },
  { category: "Públicos", name: "TV Senado" },
  { category: "Públicos", name: "TV Câmara" },
  { category: "Notícias", name: "RedeTV" },
  { category: "Notícias", name: "New" },
  { category: "Notícias", name: "TVD News" },
  { category: "Notícias", name: "Euro News" },
  { category: "Notícias", name: "Band News" },
  { category: "Notícias", name: "RN" },
  { category: "Notícias", name: "CNN Brasil" },
  { category: "Notícias", name: "Telesur" },
  { category: "Notícias", name: "Exitosa" },
  { category: "Notícias", name: "JP News" },
  { category: "Notícias", name: "Fox News" },
  { category: "Notícias", name: "Bloomberg" },
  { category: "Notícias", name: "CNBC" },
  { category: "Notícias", name: "Times Now" },
  { category: "Filmes e Séries", name: "Mider" },
  { category: "Filmes e Séries", name: "LMC" },
  { category: "Filmes e Séries", name: "Retro" },
  { category: "Filmes e Séries", name: "Ultra" },
  { category: "Filmes e Séries", name: "Family Series" },
  { category: "Filmes e Séries", name: "Movies" },
  { category: "Filmes e Séries", name: "Prime Box Brazil" },
  { category: "Filmes e Séries", name: "Film & Arts" },
  { category: "Filmes e Séries", name: "AMC" },
  { category: "Filmes e Séries", name: "ISTV" },
  { category: "Filmes e Séries", name: "Canal Sony" },
  { category: "Filmes e Séries", name: "TNT Series" },
  { category: "Filmes e Séries", name: "Space" },
  { category: "Filmes e Séries", name: "TCM HD" },
  { category: "Filmes e Séries", name: "Cinemax" },
  { category: "Filmes e Séries", name: "Lifetime HD" },
  { category: "Filmes e Séries", name: "Top Action" },
  { category: "Infantil", name: "Kios" },
  { category: "Infantil", name: "ID" },
  { category: "Infantil", name: "Otaku" },
  { category: "Infantil", name: "Leo & Lully" },
  { category: "Infantil", name: "Yupi" },
  { category: "Infantil", name: "Hallo!" },
  { category: "Infantil", name: "Discovery Kids" },
  { category: "Infantil", name: "Cartoon Network" },
  { category: "Infantil", name: "Tooncast" },
  { category: "Infantil", name: "Cartoonito" },
  { category: "Esportes", name: "Fish TV" },
  { category: "Esportes", name: "Unique Sports" },
  { category: "Esportes", name: "Cazé TV" },
  { category: "Esportes", name: "Band Sports HD" },
  { category: "Esportes", name: "Fuel TV" },
  { category: "Esportes", name: "ESPN" },
  { category: "Esportes", name: "ESPN 2" },
  { category: "Esportes", name: "ESPN 3" },
  { category: "Esportes", name: "ESPN 4" },
  { category: "Esportes", name: "ESPN 5" },
  { category: "Esportes", name: "TNT Sports" },
  { category: "Esportes", name: "Trace Sport Stars" },
  { category: "Agronegócio", name: "Canal Rural" },
  { category: "Agronegócio", name: "AgroBrasil" },
  { category: "Agronegócio", name: "Terra Viva" },
  { category: "Agronegócio", name: "AgroCanal" },
  { category: "Agronegócio", name: "Canal do Boi" },
  { category: "Documentários", name: "Discovery" },
  { category: "Documentários", name: "Animal Planet" },
  { category: "Documentários", name: "Discovery Turbo" },
  { category: "Documentários", name: "Discovery Science" },
  { category: "Documentários", name: "Discovery Theater" },
  { category: "Documentários", name: "Discovery World" },
  { category: "Documentários", name: "HGTV" },
  { category: "Documentários", name: "History" },
  { category: "Educativos", name: "TV Cultura" },
  { category: "Educativos", name: "Tvescala" },
  { category: "Educativos", name: "RESERVADO UNIVERSITÁRIO" },
  { category: "Educativos", name: "SescTV" },
  { category: "Religiosos / Outros", name: "TV Mundo Maior" },
  { category: "Religiosos / Outros", name: "Canção Nova" },
  { category: "Religiosos / Outros", name: "Rede Vida" },
  { category: "Religiosos / Outros", name: "RS21" },
  { category: "Religiosos / Outros", name: "TV Evangelizar" },
  { category: "Religiosos / Outros", name: "Novo Tempo" },
  { category: "Religiosos / Outros", name: "EWTN" },
  { category: "Religiosos / Outros", name: "Rede Gênesis" },
  { category: "Étnicos", name: "NHK" },
];

// Re-export as CHANNELS for backward compatibility if needed, 
// though we'll update the component to use the correct list.
export const CHANNELS = ULTRA_CHANNELS;
